# Work directory
work_dir: ""

# In case if you want to use only one application
# You can specify it in default_app_id
default_app_id: ""

# If set to true 
# Only default_app_id will be used
force_default_id: false

# TEMPLATE TO ADD A PROGRAM 
# FOR YOU TO COPY
template:
  TheProgram: # Like a short program name or ID (e. steam: , SPOTIFY: , VSCode: , EpicGamesLauncher)
    name: The Program # Name that will be displayed in the console 
    enable: true # Enable/Disable detection and display of this program
    executable: Program.exe # Program Executable process that is detected when focused
    app_id: 111111111111111111 # Discord Application Id to display Rich Presence
    discord_rpc: 
      details: Very good program # First line (May serve as about info)
      state: Enjoying using Program # Second line (May serve as action in program)
      large_image: large_image # id specified in dev portal for big image
      large_text: Large Image # Description text that pop up on mouse hover
      small_image: small_image # id specified in dev portal for corner image
      small_text: Small Image # Description text that pop up on mouse hover
      # Add up to TWO buttons
      # label is button text, url is destination after button is pressed
      buttons: [ 
        { 
          label: "button1", url: "https://google.com"
        },
        {
          label: "button2", url: "https://none.com"
        }
      ]
    custom_rpc_executable_path: "your\\path\\to\\script\\TheProgramRPCScript.py" # custom_rpc_exe


# LIST OF PROGRAMS TO DISPLAY
programs:

  AyuGram:
    name: AyuGram Desktop
    enable: false
    executable: ayugram.exe
    app_id:  #None ID
    discord_rpc:
      state: Messaging privately.
      large_image: 1

  BraveBrowser:
    name: Brave Browser
    enable: true
    executable: brave.exe
    app_id: 1388726055736442942
    discord_rpc:
      state: Browsing the web.
      large_image: 1

  Clipchamp:
    name: Clipchamp
    enable: true
    executable: Clipchamp.exe
    app_id: 1266991923625984064 #Old ID
    discord_rpc:
      state: Editing a video.
      large_image: 1

  cmd:
    name: cmd
    enable: true
    executable: cmd.exe
    app_id: 1388819762896830604 #Using Windows Terminal app_id
    discord_rpc:
      state: Using the command line.
      large_image: 1

  Discord:
    name: Discord 
    enable: true
    executable: Discord.exe 
    app_id: 1262946659701096498 #Old ID
    discord_rpc: 
      state: Chatting.
      large_image: 1
    
  EpicGamesLauncher: 
    name: Epic Games Launcher
    enable: true
    executable: EpicGamesLauncher.exe
    app_id: 1388827424795394239
    discord_rpc:
      state: Picking a game to play.
      large_image: 1

  FileExplorer:
    name: File Explorer
    enable: true
    executable: explorer.exe
    app_id: 1388738026821259314
    discord_rpc:
      state: Browsing files.
      large_image: 1
  
  GitHubDesktop:
    name: GitHubDesktop
    enable: true
    executable: GitHubDesktop.exe
    app_id: 1388829761463386203
    discord_rpc:
      state: Managing repositories.
      large_image: 1

  MicrosoftEdge:
    name: Edge Browser
    enable: true
    executable: msedge.exe
    app_id: 1389356353348440176
    discord_rpc:
      state: Browsing the web.
      large_image: 1

  notepad:
    name: Notepad
    enable: true
    executable: Notepad.exe
    app_id: 1388825324787208192
    discord_rpc:
      state: Taking down notes.
      large_image: 1

  NZXT_CAM:
    name: NZXT CAM
    enable: true
    executable: NZXT CAM.exe
    app_id: 1389359521431814266
    discord_rpc:
      state: Monitoring system performance.
      large_image: 1
      
  Photos:
    name: Photos
    enable: true
    executable: Photos.exe
    app_id: 1389017465182486568
    discord_rpc:
      state: Browsing photos.
      large_image: 1

  RiotClient:
    name: Riot Client
    enable: true
    executable: Riot Client.exe
    app_id: 1389360664673521805
    discord_rpc:
      state: Accessing Riot Games titles.
      large_image: 1

  Spotify:
    name: Spotify
    enable: true
    executable: Spotify.exe
    app_id: 1388898282457141270
    discord_rpc:
      state: Choosing music to listen to.
      large_image: 1

  ShareX:
    name: ShareX
    enable: true
    executable: ShareX.exe
    app_id: 1389361256141685059
    discord_rpc:
      state: Capturing and sharing.
      large_image: 1

  steamwebhelper:
    name: steamwebhelper
    enable: true
    executable: steamwebhelper.exe
    app_id: 1389363389083680921
    discord_rpc:
      state: Browsing the game library.
      large_image: 1

  SystemSettings:
    name: SystemSettings
    enable: false # Deprecated, now it is ApplicationFrameHost.exe
    executable: SystemSettings.exe
    app_id: 1267241964353355886
    discord_rpc:
      state: Changing PC settings.
      large_image: 2 #Do not change

  Taskmgr:
    name: Taskmgr
    enable: true
    executable: Taskmgr.exe
    app_id: 1388898666131226674
    discord_rpc:
      state: Monitoring system processes.
      large_image: 1
      
  Telegram:
    name: Telegram
    enable: true
    executable: Telegram.exe
    app_id: 1389072642958430358
    discord_rpc:
      state: Chatting with friends.
      large_image: 1

  VLCplayer:
    name: VLC Media Player
    enable: false # Disabled for now, enable if you want to use it
    executable: vlc.exe
    app_id: 1262981573305700352
    discord_rpc:
      state: Playing media.
      large_image: 1
  
  voicemeeter8x64:
    name: voicemeeter8x64
    enable: false # Disabled for now, enable if you want to use it
    executable: voicemeeter8x64.exe
    app_id: 1262944099531755551
    discord_rpc:
      state: Configuring audio.
      large_image: 1

  WindowsTerminal:
    name: WindowsTerminal
    enable: true
    executable: WindowsTerminal.exe
    app_id: 1388819762896830604
    discord_rpc:
      state: Using the terminal.
      large_image: 1
      
  WsaClient:
    name: WsaClient
    enable: false # Disabled for now, enable if you want to use it
    executable: WsaClient.exe
    app_id: 1267985784644829266
    discord_rpc:
      state: Using an Android app.
      large_image: 1

# CUSTOM RPCS
  "Colin's Valorant RPC":
    name: Valorant
    enable: false # Deprecated, under development
    executable: VALORANT-Win64-Shipping.exe
    custom_rpc_executable_path: python presets/valorant/VALORANT-Win64-Shipping.py

  "Dyl's Roblox RPC":
    name: Roblox
    enable: true
    executable: RobloxPlayerBeta.exe
    app_id: 1155101158780702830
    discord_rpc:
      buttons: [
          {
            "label": "Join server" , "url": "roblox://experiences/start?placeId={PLACEID}&gameInstanceId={JOBID}"
            }, 
          {
            "label": "View on website" ,"url": "https://www.roblox.com/games/{PLACEID}/"
            }
          ]
    custom_rpc_executable_path: python src/modules/roblox.py

  "Semebody's LoL RPC":
    name: League-of-legends
    enable: false # Deprecated, under development
    executable: LeagueOfLegends.exe
    custom_rpc_executable_path: python presets/league-of-legends/lol_rpc.py
