# This is the main configuration file for all your applications.
# Add new entries under the 'programs' section.

# =====================================================================================
# Default Application ID

# Used for External Mode if a program doesn't have its own app_id specified.
# Leave blank to disable.

default_app_id: ''


# =====================================================================================
# Program Configurations examples

programs:
  BraveBrowser:
    name: Brave Browser
    executable: brave.exe
    enable: false # Set to 'true' to enable this RPC, 'false' to disable.
    app_id: 1388726055736442942   # 'app_id' is OPTIONAL. It is required for 'external' mode, but ignored by 'integrated' mode.
    discord_rpc:
      details: "Browsing the web"
      state: "Looking at cool sites"
      large_image: "brave" # Asset key for the large image
      large_text: "Brave Browser"

  Visual-Studio-Code:
    name: "Visual Studio Code"
    executable: "Code.exe"
    enable: false
    app_id: 1388723289567789209
    discord_rpc:
      details: "Editing a Python file"
      state: "Workspace: uDRP"
      large_image: "vscode"
      large_text: "Editing {file_name}" # Example of a future dynamic variable
      small_image: "python"
      small_text: "Python"
      buttons:
        - label: "View on GitHub"
          url: "https://github.com/Purple-Palm/Universal-Discord-Rich-Presence"

  Spotify:
    name: "Spotify"
    executable: "Spotify.exe"
    enable: false
    discord_rpc:
      presence_type: "listening"  # For 'listening' or 'streaming', set the presence_type. Defaults to 'playing'.
      details: "Listening to my favorite artist"
      state: "Discover Weekly"
      large_image: "spotify_logo"
      large_text: "Spotify"


# =====================================================================================
# --- TEMPLATE SECTION ---
# Use this as a guide to create your own entries.
# =====================================================================================

template:
  TheProgram:
    # The display name for your application.
    name: The Program
    # The exact executable name (case-insensitive). Find it in Task Manager.
    executable: Program.exe
    # Set to 'true' to enable this RPC, 'false' to disable.
    enable: true
    # OPTIONAL: Required for 'external' mode. Ignored by 'integrated' mode.
    # Get this from your Discord Developer Portal application.
    app_id: 111111111111111111

    # All Rich Presence details go under this key.
    discord_rpc:
      # OPTIONAL: Can be 'playing' (default), 'streaming', or 'listening'.
      presence_type: playing

      # REQUIRED for 'streaming' type. The URL must be a valid Twitch or YouTube link.
      # url: "https://www.twitch.tv/yourchannel"

      # The first line of text under the application name.
      details: "Very good program"
      # The second line of text.
      state: "Enjoying using Program"

      # The asset key for the large image, uploaded in your Discord Dev Portal.
      large_image: "large_image_key"
      # The text that appears when hovering over the large image.
      large_text: "Large Image Hover Text"

      # OPTIONAL: The asset key for the small image.
      small_image: "small_image_key"
      # OPTIONAL: The text that appears when hovering over the small image.
      small_text: "Small Image Hover Text"

      # OPTIONAL: A list of up to two buttons.
      buttons:
        - label: "Button 1 Label"
          url: "https://your-url-here.com"
        - label: "Button 2 Label"
          url: "https://another-url.com"