# --- Default Application ID ---
# Used for any program that does not have a specific 'app_id' assigned.
# Create one application in the Discord Dev Portal, upload all your assets to it,
# and paste its ID here.
default_app_id: '1388723289567789209' # Replace with your actual default App ID

# =====================================================================================
# --- Program Configurations ---
# A consolidated, alphabetized list of all applications.
# =====================================================================================
programs:
  BraveBrowser:
    name: Brave Browser
    executable: brave.exe
    enable: true
    discord_rpc:
      details: Browsing the web
      large_image: 'brave-browser'
  CheatEngine:
    name: Cheat Engine
    executable: cheatengine-x86_64-SSE4-AVX2.exe
    enable: true
    discord_rpc:
      details: "Looking for values"
      large_image: 'cheat-engine'
  Chrome:
    name: Google Chrome
    executable: chrome.exe
    enable: true
    discord_rpc:
      details: Browsing the web
      large_image: 'google-chrome'
  FileExplorer:
    name: File Explorer
    executable: explorer.exe
    enable: true
    discord_rpc:
      details: Browsing files
      large_image: 'explorer'
  FileZilla:
    name: FileZilla
    executable: filezilla.exe
    enable: true
    discord_rpc:
      details: Managing FTP connections
      large_image: 'filezilla'
  Firefox:
    name: Firefox
    executable: firefox.exe
    enable: true
    discord_rpc:
      details: Browsing the web
      large_image: 'firefox'
  GitHubDesktop:
    name: GitHub Desktop
    executable: GitHubDesktop.exe
    enable: true
    discord_rpc:
      details: Managing repositories
      large_image: 'github'
  MicrosoftEdge:
    name: Microsoft Edge
    executable: msedge.exe
    enable: true
    discord_rpc:
      details: Browsing the web
      large_image: 'microsoft-edge'
  MSI-Afterburner:
    name: MSI Afterburner
    executable: MSIAfterburner.exe
    enable: true
    discord_rpc:
      details: Monitoring hardware
      large_image: 'msiafterburner'
  Notepad:
    name: Notepad
    executable: Notepad.exe
    enable: true
    discord_rpc:
      details: Taking notes
      large_image: 'notepad'
  Postman:
    name: Postman
    executable: Postman.exe
    enable: true
    discord_rpc:
      details: Testing APIs
      large_image: 'postman'
  ShareX:
    name: ShareX
    executable: ShareX.exe
    enable: true
    discord_rpc:
      details: Capturing and sharing
      large_image: 'sharex'
  Spotify:
    name: Spotify
    executable: Spotify.exe
    enable: true
    discord_rpc:
      presence_type: listening
      details: Listening to music
      large_image: 'spotify'
  SublimeText:
    name: Sublime Text
    executable: sublime_text.exe
    enable: true
    discord_rpc:
      details: Editing text and code
      large_image: 'sublime-text'
  Taskmgr:
    name: Task Manager
    executable: Taskmgr.exe
    enable: true
    discord_rpc:
      details: Monitoring system processes
      large_image: 'task-manager'
  Telegram:
    name: Telegram
    executable: Telegram.exe
    enable: true
    discord_rpc:
      details: Chatting with friends
      large_image: 'telegram'
  VLC:
    name: VLC Media Player
    executable: vlc.exe
    enable: true
    discord_rpc:
      details: Watching a video
      large_image: 'vlc'
  VisualStudioCode:
    name: Visual Studio Code
    executable: Code.exe
    enable: false # VSCode has its own RPC.
    discord_rpc:
      details: Editing code
      state: In a workspace
      large_image: 'vscode_icon'
  WindowsTerminal:
    name: Windows Terminal
    executable: WindowsTerminal.exe
    enable: true
    discord_rpc:
      details: Using the command line
      large_image: 'terminal'

# =====================================================================================
# --- TEMPLATE SECTION ---
# =====================================================================================
template:
  TheProgram:
    name: The Program
    executable: Program.exe
    enable: true
    app_id: 123456789012345678 # Optional, overrides the default_app_id.

    discord_rpc:
      presence_type: playing
      details: "Very good program"
      state: "Enjoying using Program"
      large_image: "large_image_key"
      
      timestamps:
        # Option 1: No Timer (Default Behavior)
        # To show no timer, simply omit the 'timestamps' section or leave it empty.

        # Option 2: Elapsed Time
        # Shows "00:01 elapsed" and counts up.
        elapsed: true

        # Option 3: Countdown Timer
        # Shows "01:30 remaining" and counts down.
        # Use a Unix timestamp converter to get the number for a future time.
        # end: 1751552400
